// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt4ZZBvvp1WBwf-fYSvhcIlupSkhCjebM',
    appId: '1:283984929830:web:8a090852a7daf0f589f2e7',
    messagingSenderId: '283984929830',
    projectId: 'fir-flutter-codelab-c1841',
    authDomain: 'fir-flutter-codelab-c1841.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c1841.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvsxHEboffw76RFmN6JUDBoHLoo654nnM',
    appId: '1:283984929830:android:c0777a0527c68d9c89f2e7',
    messagingSenderId: '283984929830',
    projectId: 'fir-flutter-codelab-c1841',
    storageBucket: 'fir-flutter-codelab-c1841.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ptlYBoFFwzbCXj-Q2s-M8kguLtjjbUQ',
    appId: '1:283984929830:ios:3f09fc4537d80b3b89f2e7',
    messagingSenderId: '283984929830',
    projectId: 'fir-flutter-codelab-c1841',
    storageBucket: 'fir-flutter-codelab-c1841.appspot.com',
    iosClientId: '283984929830-t8kcf4gu9qime5ulctr8pgsg9gt8mqev.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ptlYBoFFwzbCXj-Q2s-M8kguLtjjbUQ',
    appId: '1:283984929830:ios:3f09fc4537d80b3b89f2e7',
    messagingSenderId: '283984929830',
    projectId: 'fir-flutter-codelab-c1841',
    storageBucket: 'fir-flutter-codelab-c1841.appspot.com',
    iosClientId: '283984929830-t8kcf4gu9qime5ulctr8pgsg9gt8mqev.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
